<a href="https://colab.research.google.com/github/sanee3147/Linear-Algebra/blob/main/%EC%8B%A4%EC%8A%B5zero2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def print_val(x):
  print("Type", type(x))
  print("Shape", x.shape)
  print("값:\n", x)
  print(" ")

x = np.array([1,2,3])
print_val(x)

x[0] = 5
print_val(x)

y = np.array([[1,2,3], [4,5,6]])
print_val(y)

a = np.ones((3,2))
print_val(a)

a = np.zeros((2,2))
print_val(a)

a = np.eye(3,3)
print_val(a)

a = np.random.random(4,4)
print_val(a)

a = np.random.randn(4,4)
print_val(a)

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print_val(a)

b = a[:2, 1:3]
print_val(b)

row1 = a[1, :]
print_val(row1)

m1 = np.array([[1,2], [3,4]], dtype=np.float64)
m2 = np.array([[5,6], [7,8]], dtype=np.float64)

print_val(m1 + m2)
print_val(np.add(m1, m2))

print_val(m1 - m2)
print_val(np.subtract(m1, m2))

print_val(m1 * m2)
print_val(np.multiply(m1, m2))

print_val(m1 / m2)
print_val(np.divide(m1, m2))

print_val(np.sqrt(m1))

m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6], [7,8]])
v1 = np.array([9,10])
v1 = np.array([11,12])

print_val(m1)
print_val(m2)
print_val(v1)
print_val(v2)

print_val(v1.dot(v2))
print_val(np.dot(v1, v2))

print_val(m1.dot(v1))
print_val(np.dot(v1, v2))

print_val(m1.dot(m2))
print_val(m1.dot(m1, m2))

print_val(m1)
print_val(m1.T)

print_val(np.sum(m1))
print_val(np.sum(m1, axis=0))
print_val(np.sum(m1, axis=1))

m1 = np.array([[1,2,3], [4,5,6]])
print m1
print m1.shape

print np.sum(m1)
print np.sum(m1, axis=0)
print np.sum(m1, axis=1)

m1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9],
               [10,11,12]])
m2 = np.zeros_like(m1)
print_val(m1)
print_val(m2)

import matplotlib.pyplot as plt
%matplotlib inline

x = np.arange(0, 10, 0.1)
y = np.sin(x)

plt.plot(x,y)

y_sin = np.sin(x)
y_cos = np.cos(x)

plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('sin and cos')
plt.legend(['sin', 'cos'])

plt.show()

plt.subplot(2, 1, 1)
plt.plot(x, y_sin)
plt.title('sin')

plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('cos')

plt.show()


Type <class 'numpy.ndarray'>
Shape (3,)
값:
 [1 2 3]
 
Type <class 'numpy.ndarray'>
Shape (3,)
값:
 [5 2 3]
 
Type <class 'numpy.ndarray'>
Shape (2, 3)
값:
 [[1 2 3]
 [4 5 6]]
 
Type <class 'numpy.ndarray'>
Shape (3, 2)
값:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
 
Type <class 'numpy.ndarray'>
Shape (2, 2)
값:
 [[0. 0.]
 [0. 0.]]
 
Type <class 'numpy.ndarray'>
Shape (3, 3)
값:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
